#!/bin/bash

#Colours
greenColour="\e[0;32m\033[1m"
endColour="\033[0m\e[0m"
redColour="\e[0;31m\033[1m"
blueColour="\e[0;34m\033[1m"
yellowColour="\e[0;33m\033[1m"
purpleColour="\e[0;35m\033[1m"
turquoiseColour="\e[0;36m\033[1m"
grayColour="\e[0;37m\033[1m"

trap "rm -f /tmp/ip.txt > /dev/null 2>&1; exit" SIGINT SIGTERM

/usr/bin/curl https://check.torproject.org/ --silent > /tmp/ip.txt
if [ $? -ne 0 ]; then
	echo -e "\n${redColour}[!]${blueColour} check.torproject.org parece estar caído.\n${endColour}"
	rm -f /tmp/ip.txt
	exit
fi

ip=$(cat /tmp/ip.txt | grep -oP "\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}" | sort -u)
echo -e "\n${yellowColour}[+]${blueColour} Tu IP es${endColour} ${ip}"

if cat /tmp/ip.txt | grep "Sorry. You are not using Tor." > /dev/null 2>&1 ; then
	echo -e "${yellowColour}[-]${blueColour} No enrutas por un circuito Tor\n${endColour}"
else
	echo -e "${greenColour}[+]${redColour} Estás correctamente enrutado por Tor  =)\n${endColour}"
fi

rm -f /tmp/ip.txt


