#! /bin/sh

sxhkd &
wmname LG3D &
compton --config ~/.config/compton/compton.conf &
~/.config/polybar/launch.sh &
#xrandr --output DP-1 --primary --mode 1920x1080 --rate 144.00 &
feh --bg-fill ~/Documents/wallpaper.png &

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_sidie
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.52
# En modo monocle, las ventanas dejan un espacio hasta la polybar.
# Añadir este valor negativo lo arregla
bspc config top_monocle_padding  -5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a com-sittinglittleduck-DirBuster-Start state=floating
bspc rule -a Caja state=floating
bspc rule -a discord desktop='^9' follow=on
bspc rule -a "Spotify:*:*" desktop='^10' follow=on

# Reglas por defecto
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
